### ISSUE TITLE
Feature: User can favorite a dog image 

### ISSUE THREAD

**Issue by David-Gonzalez11** [David-Gonzalez11/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user sees an image of a dog they like then they can click the star icon and it will indicate that they favorited that image.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Define a function name renderImages 
- [x] Update entry rendering function to include a paw icon for each rendered image
- [x] Ensure that each rendered entry is given a `data-entry-id` attribute indicating which image it is.
- [x] Change the color of the paw icon to ensure that the user has clicked that icon to favorite it
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
