### ISSUE TITLE
Feature: User can add notes to their favorite images 

### ISSUE THREAD

**Issue by David-Gonzalez11** [David-Gonzalez11/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can view a list of their favorite images of dogs and can write notes about each image
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an <a> tag to the navbar next to the title
- [x] Add an event Listener to the anchor tag to show the favorite pages when clicked
- [x] Hide the main page and only show the favorites
- [x] Add a text area input so that the user can input notes 
- [x] Ensure that refreshing the page shows the same view as before refreshing
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
