### ISSUE TITLE
Feature: User can delete photos/notes from their favorites page

### ISSUE THREAD

**Issue by David-Gonzalez11** [David-Gonzalez11/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the Delete button then a modal will be displayed to confirm or cancel the deletion

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click target for deleting an image to the image container 
- [x] Show a confirmation modal when the user clicks the Delete  click target.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the image/notes from the data model and the page if the user clicks Delete.
- [x] Show the Favorites list if the user clicks Delete.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
